openapi: 3.0.0
info:
  title: Leaderboard API
  description: REST API for leaderboards
  version: 1.0.0

paths:
  /api/challenges/{challengeId}/leaderboard:
    get:
      summary: Get leaderboard for a specific challenge
      parameters:
        - name: challengeId
          in: path
          required: true
          description: ID of the challenge
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                leaderboard:
                  - rank: 1
                    username: user1
                    score: 100
                  - rank: 2
                    username: user2
                    score: 90
                  - rank: 3
                    username: user3
                    score: 80
