openapi: 3.0.0
info:
  title: User Profile API
  description: REST API for user profiles
  version: 1.0.0

paths:
  /api/users/{userId}:
    get:
      summary: Get user details
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                username: example_user
                email: user@example.com

    put:
      summary: Update user profile
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
              required:
                - username
                - email
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              example:
                message: "Profile updated successfully"
