openapi: 3.0.0
info:
  title: User Authentication API
  description: REST API for user authentication
  version: 1.0.0

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              example:
                message: User registered successfully
                user:
                  id: 1
                  username: example_user
                  email: user@example.com

  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              example:
                message: Login successful
                token: jwt_token

  /api/auth/logout:
    post:
      summary: User logout
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              example:
                message: Logout successful

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
